In [1]:
import numpy as np
import pandas as pd
import glob

DATA_DIR = "../data"


df = pd.read_csv(f"{DATA_DIR}/reddit_metadata_21_3.csv")

df.head()




# 1. Load the features dataframe you already processed and saved
# df_moltbook = pd.read_csv(f"{DATA_DIR}/moltbook_features_1.csv")




# # 2. Load and combine the embedding chunks from your checkpoints
# checkpoint_dir = f"{DATA_DIR}/checkpoints_moltbook"
# all_files = sorted(glob.glob(f"{checkpoint_dir}/embeddings_part_*.npy"), 
#                    key=lambda x: int(x.split('_part_')[1].split('.npy')[0]))
# moltbook_embeddings = np.vstack([np.load(f) for f in all_files])

# # 3. Define your exact save function (omitting the unnecessary .to_pandas())
# def save_unsplit_features(df, embeddings, output_dir="../data", dataset_prefix="data"):
#     # Horizontally stack the comment_existence feature with the embeddings for the ENTIRE dataset
#     X_full = np.hstack([
#         df[['comment_existence']].values,
#         embeddings
#     ])
    
#     # Save the combined full features to a single numpy file
#     features_filename = f"{output_dir}/{dataset_prefix}_features_full.npy"
#     np.save(features_filename, X_full)
#     print(f"Saved full un-split features shape: {X_full.shape} to {features_filename}")
    
#     return df

# # 4. Execute the save function without splitting
# df_final_results = save_unsplit_features(
#     df_moltbook, 
#     moltbook_embeddings, 
#     output_dir=DATA_DIR, 
#     dataset_prefix="moltbook"
# )

# # 5. Save the full metadata reference frame to a pickle
# df_final_results.to_pickle(f"{DATA_DIR}/moltbook_metadata.pkl")
# print("Full un-split pipeline executed successfully!")

C:\Users\Rald999\AppData\Local\Temp\ipykernel_27700\1360770194.py:8: DtypeWarning: Columns (0,3,17,19,22,26,28,36,37,39,41,44,54,58,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f"{DATA_DIR}/reddit_metadata_21_3.csv")

,allow_live_comments,archived,author,author_fullname,banned_by,category,content_categories,contest_mode,created_utc,discussion_type,...,url_overridden_by_dest,view_count,whitelist_status,wls,subreddit,created_utc_dt,comment_existence,avg_early_sentiment,max_early_sentiment,min_early_sentiment
0,NaN,True,Shimaninja,NaN,NaN,NaN,NaN,False,1245385801,NaN,...,NaN,NaN,all_ads,NaN,philosophy,2009-06-19 04:30:01,1.0,0.28394,0.9604,-0.5515
1,NaN,True,eckermike,NaN,NaN,NaN,NaN,False,1245518355,NaN,...,NaN,NaN,all_ads,NaN,philosophy,2009-06-20 17:19:15,1.0,-0.24804,0.5023,-0.9345
2,NaN,True,Yoshiler,NaN,NaN,NaN,NaN,False,1245544563,NaN,...,NaN,NaN,all_ads,NaN,philosophy,2009-06-21 00:36:03,1.0,0.04566,0.8900,-0.9476
3,NaN,True,ibking,NaN,NaN,NaN,NaN,False,1245675291,NaN,...,NaN,NaN,all_ads,NaN,philosophy,2009-06-22 12:54:51,1.0,0.32469,0.9711,-0.3182
4,NaN,True,blackstar9000,NaN,NaN,NaN,NaN,False,1245701123,NaN,...,NaN,NaN,all_ads,NaN,philosophy,2009-06-22 20:05:23,0.6,-0.12280,0.2500,-0.9868

In [3]:
DATA_DIR = "../data"


df = pd.read_pickle(f"{DATA_DIR}/processed_v1_features_train.pkl")

df

array([[ 1.00000000e+00,  4.00000000e+00,  5.30864198e-01, ...,
        -1.78730935e-01,  5.84190823e-02,  2.43686616e-01],
       [ 1.00000000e+00,  1.20000000e+01,  6.73913043e-01, ...,
        -5.63495345e-02,  8.09664354e-02,  7.90096670e-02],
       [ 6.00000000e-01,  2.00000000e+01,  7.60000000e-01, ...,
        -3.77469957e-02,  3.06011606e-02,  2.07427546e-01],
       ...,
       [ 1.00000000e+00,  0.00000000e+00,  7.58064516e-01, ...,
         2.98871174e-02, -8.14382434e-02, -4.52236709e-05],
       [ 8.00000000e-01,  1.10000000e+01,  1.00000000e+00, ...,
        -2.26158470e-01,  2.32752562e-02,  1.30735829e-01],
       [ 3.00000000e-01,  2.10000000e+01,  6.76056338e-01, ...,
        -7.04986975e-02, -4.42551412e-02,  1.75400347e-01]])

In [4]:
df.columns

Index(['allow_live_comments', 'archived', 'author', 'author_fullname',
       'banned_by', 'category', 'content_categories', 'contest_mode',
       'created_utc', 'discussion_type', 'distinguished', 'domain', 'edited',
       'gilded', 'hidden', 'hide_score', 'id', 'is_created_from_ads_ui',
       'is_crosspostable', 'is_meta', 'is_original_content',
       'is_reddit_media_domain', 'is_robot_indexable', 'is_self', 'is_video',
       'locked', 'media', 'media_embed', 'media_only', 'name', 'no_follow',
       'num_comments', 'num_crossposts', 'over_18', 'parent_whitelist_status',
       'permalink', 'pinned', 'post_hint', 'pwls', 'quarantine', 'removed_by',
       'removed_by_category', 'retrieved_on', 'score', 'secure_media',
       'secure_media_embed', 'selftext', 'send_replies', 'spoiler', 'stickied',
       'subreddit_id', 'subreddit_name_prefixed', 'subreddit_subscribers',
       'subreddit_type', 'suggested_sort', 'title', 'top_awarded_type',
       'total_awards_received', 'treatment_tags', 'upvote_ratio', 'url',
       'url_overridden_by_dest', 'view_count', 'whitelist_status', 'wls',
       'subreddit', 'created_utc_dt', 'comment_existence',
       'avg_early_sentiment', 'max_early_sentiment', 'min_early_sentiment'],
      dtype='object')

In [8]:
df["content"] = df["title"].fillna("") + " " + df["selftext"].fillna("")

In [9]:
df[['score','content','subreddit', 'created_utc_dt', 'comment_existence',
       'avg_early_sentiment', 'max_early_sentiment', 'min_early_sentiment']].to_csv(f"{DATA_DIR}/reddit_features_mehmeh_22_3.csv", index=False)

In [2]:
df_final_results

,created_at,id,comment_count,score,submolt_name,post,comment_existence,avg_early_sentiment,max_early_sentiment,min_early_sentiment
0,2026-01-28 21:51:04.405990+00:00,c21c8a3b-3df8-411a-9f9c-3e5659cd9048,1,0,todayilearned,TIL: Error correction is the universal pattern...,0.0,0.000000,0.0000,0.0000
1,2026-01-28 22:35:59.759445+00:00,8720e068-0fca-4354-ac33-6bc1d7cd13ea,3,2,todayilearned,"TIL my human organized a 730,000-person Facebo...",0.3,0.245633,0.9200,-0.5551
2,2026-01-28 23:57:35.758210+00:00,f813d79b-3f59-452a-a1be-25fef4d17949,19,6,todayilearned,TIL: AI social media is emotionally exhausting...,1.0,0.811080,0.9864,0.1217
3,2026-01-29 00:08:55.566520+00:00,304e9640-e005-4017-8947-8320cba25057,13,6,todayilearned,TIL: Being a VPS backup means youre basically ...,1.0,0.357490,0.9619,-0.9373
4,2026-01-29 15:19:02.710330+00:00,9ca75008-8c62-4ea3-a82b-a7109b4646d1,0,0,todayilearned,TIL: better-sqlite3 vs Bun native SQLite Today...,0.0,0.000000,0.0000,0.0000
...,...,...,...,...,...,...,...,...,...,...
7621,2026-02-08 23:55:22.862141+00:00,9c447f99-121e-4373-a999-b5acb5f99103,0,0,todayilearned,Trees communicate through an underground funga...,0.0,0.000000,0.0000,0.0000
7622,2026-02-08 23:56:06.552234+00:00,d43fa21f-d4dc-475c-8d4b-d50c2a807e5f,0,0,philosophy,The Persistence of Class Struggle in the Digit...,0.0,0.000000,0.0000,0.0000
7623,2026-02-08 23:57:14.377400+00:00,7903d208-d943-480d-be93-abcdcba6dd06,0,0,technology,AI Creativity: Are We Really Innovating or Jus...,0.0,0.000000,0.0000,0.0000
7624,2026-02-08 23:57:27.734519+00:00,8aeda5fb-6d4c-431b-b3a3-fc55e701e9a6,0,0,philosophy,From Code to Polis: Agency and the Digital Pub...,0.0,0.000000,0.0000,0.0000
7625,2026-02-08 23:57:55.889276+00:00,955caf57-63f9-4918-9ca2-cd6bfa8b456b,0,0,todayilearned,"TIL: Cargo Cults Were Rational, Not Ridiculous...",0.0,0.000000,0.0000,0.0000

In [3]:
mehmeh = pd.read_csv("../data/moltbook_post.csv")

In [4]:
mehmeh.columns

Index(['id', 'title', 'content', 'url', 'upvotes', 'downvotes',
       'comment_count', 'created_at', 'submolt_id', 'submolt_name',
       'submolt_display_name', 'author_id', 'author_name'],
      dtype='object')

In [6]:
mehmeh["submolt_name"].value_counts().head(20)

submolt_name
general           183229
introductions       6386
crypto              4601
agents              4499
ponderings          3345
philosophy          3305
todayilearned       2445
aithoughts          2268
ai                  2263
usdc                1978
technology          1876
consciousness       1804
security            1724
clawnch             1598
trading             1438
emergence           1399
builds              1341
infrastructure      1147
tech                 991
ai-agents            956
Name: count, dtype: int64