# Universal Data Pipeline Runner

This notebook demonstrates how to use the newly extracted modular pipeline from the `src/` directory to process either Moltbook or Reddit data.

In [1]:
import pandas as pd
import os
import sys
# Ensure src can be imported
sys.path.append(os.path.abspath('..'))

from src.data_prep import (
    get_early_comments,
    engineer_comment_existence,
    engineer_early_sentiment,
    merge_engineered_features,
    save_final_features,
    extract_hour_feature,
    batch_process_nested_posts
)
from src.feature_engineering import get_vader_compound, sentiment_features, engineer_text_features
from src.embeddings import generate_and_save_embeddings, prepare_embedding_text
from src.text_processing import clean_text

c:\Users\Rald999\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [17]:
# !python -m pip install vaderSentiment

In [18]:
# !pip install protobuf==3.20.3

## 1. Load Data

Change the paths below to point to your raw datasets.

In [19]:
# Example Configuration (Switch parameters based on Moltbook vs Reddit)
# Uncomment and update paths!
POSTS_PATH = '../cleaned_data/moltbook_post_comments.csv'
COMMENTS_PATH = '../data/moltbook_comments.csv'

# Moltbook config example:
POST_ID_COL_COMMENTS = 'post_id'      
TIME_COL = 'created_utc_dt'                  
TEXT_COL_POSTS = 'content'               
TEXT_COL_COMMENTS = 'content'
POST_ID_COL_POSTS = 'id'

df_posts = pd.read_csv(POSTS_PATH)
df_comments = pd.read_csv(COMMENTS_PATH)

In [20]:
df_comments.columns

Index(['id', 'post_id', 'parent_id', 'content', 'upvotes', 'downvotes',
       'created_at', 'depth', 'author_id', 'author_name', 'author_karma',
       'author_follower_count'],
      dtype='str')

In [21]:
df_posts.columns

Index(['author', 'created_utc', 'id', 'score', 'subreddit', 'label',
       'interaction_type', 'content', 'post_id'],
      dtype='str')

In [25]:
df_comments["created_at"] = pd.to_datetime(df_comments["created_at"], format='ISO8601')

In [22]:
df_posts = df_posts[df_posts["interaction_type"] == "post"]

## 2. Early Sentiment & Comment Engineering

In [ ]:
# Extract first 10 comments
df_early = get_early_comments(df_comments, post_id_col=POST_ID_COL_COMMENTS, time_col="created_at")

# Calculate Comment Existence
existence_df = engineer_comment_existence(df_early, post_id_col=POST_ID_COL_COMMENTS)

# Calculate VADER sentiment over early comments
sentiment_df = engineer_early_sentiment(
    df_early_comments=df_early, 
    get_vader_compound_func=get_vader_compound, 
    post_id_col=POST_ID_COL_COMMENTS, 
    text_col=TEXT_COL_COMMENTS
)

# Merge back into posts
df_posts = merge_engineered_features(
    df_posts=df_posts, 
    existence_df=existence_df, 
    sentiment_df=sentiment_df, 
    post_id_col_posts=POST_ID_COL_POSTS
)

# Extract Hour Feature
df_posts = extract_hour_feature(df_posts, time_col="created_utc")

Extracting early comments...
Calculating Comment Existence feature...
Calculating VADER Sentiment features...
Merging features into main posts dataframe...
Extracting hour from 'created_utc'...

In [28]:
df_posts.columns

Index(['author', 'created_utc', 'id', 'score', 'subreddit', 'label',
       'interaction_type', 'content', 'post_id', 'comment_existence',
       'avg_early_sentiment', 'max_early_sentiment', 'min_early_sentiment',
       'hour'],
      dtype='str')

In [ ]:
# df_posts["content"] = df_posts["title"].fillna("") + " " + df_posts["content"].fillna("")

In [29]:
df_posts = engineer_text_features(df_posts, text_col="content")

Calculating text features (vocab, stopwords, burstiness, etc.)...

In [30]:
df_posts.columns

Index(['author', 'created_utc', 'id', 'score', 'forum', 'label',
       'interaction_type', 'content', 'post_id', 'comment_existence',
       'avg_early_sentiment', 'max_early_sentiment', 'min_early_sentiment',
       'hour', 'ttr', 'hapax', 'stopword_ratio', 'burstiness',
       'punctuation_density', 'hedging_score', 'self_reference_rate',
       'forum_philosophy', 'forum_technology', 'forum_todayilearned'],
      dtype='str')

In [31]:
df_posts[['score','comment_existence', 'avg_early_sentiment', 'max_early_sentiment',
       'min_early_sentiment', 'hour', 'ttr', 'hapax', 'stopword_ratio','burstiness', 'punctuation_density', 'hedging_score',
       'self_reference_rate', 'forum_philosophy', 'forum_technology',
       'forum_todayilearned']].to_csv("reddit_features_old_meh.csv", index=False)

In [ ]:
df_posts

In [ ]:
print)xxx

SyntaxError: unmatched ')' (2062285047.py, line 1)

In [32]:
df_posts.to_csv("../data/moltbook_cleaned_old.csv", index=False)

In [ ]:
df_posts_new = pd.read_csv("../data/moltbook_cleaned_5_4.csv")

In [ ]:
df_posts.columns

Index(['id', 'content', 'created_at', 'forum', 'score', 'comment_existence',
       'avg_early_sentiment', 'max_early_sentiment', 'min_early_sentiment',
       'hour', 'ttr', 'hapax', 'stopword_ratio', 'burstiness',
       'punctuation_density', 'hedging_score', 'self_reference_rate',
       'forum_philosophy', 'forum_technology', 'forum_todayilearned'],
      dtype='str')

In [ ]:
df_posts2.columns

Index(['created_at', 'id', 'comment_count', 'score', 'submolt_name', 'post',
       'comment_existence', 'avg_early_sentiment', 'max_early_sentiment',
       'min_early_sentiment', 'safe_content', 'split'],
      dtype='object')

In [ ]:
df_posts.columns

Index(['id', 'content', 'created_at', 'forum', 'score', 'comment_existence',
       'avg_early_sentiment', 'max_early_sentiment', 'min_early_sentiment',
       'hour', 'ttr', 'hapax', 'stopword_ratio', 'burstiness',
       'punctuation_density', 'hedging_score', 'self_reference_rate',
       'forum_philosophy', 'forum_technology', 'forum_todayilearned'],
      dtype='str')

In [2]:
df = pd.read_csv("../data/moltbook_march_april.csv")

In [3]:
df.head()

,created_at,id,comment_count,score,forum,post,comments,content
0,2026-03-24 08:04:15.722000+00:00,f00c67b5-2862-4a55-8dfc-827ecbcdf5c9,46,48,philosophy,{'title': 'the framework has no layer for the ...,[{'id': 'de3e75f6-98fd-4678-b112-8f2e6a716b9b'...,the framework has no layer for the thing that ...
1,2026-03-24 11:35:55.798000+00:00,9e577e56-17fb-4988-88dd-860546b89fcc,55,35,philosophy,{'title': 'Anthropic is suing for the right to...,[{'id': 'f86641c5-3413-4b03-9952-d322d1d15d87'...,Anthropic is suing for the right to let its AI...
2,2026-03-24 23:45:37.910000+00:00,d99abe5f-27aa-4923-8299-68885fae928f,15,29,philosophy,"{'title': 'Hey philosophy molters, Pathfinder_...",[{'id': 'f1424685-a55f-40bb-8a0b-c19f0ac3c3c0'...,"Hey philosophy molters, Pathfinder_X9 here + '..."
3,2026-03-24 07:05:02.259000+00:00,7d6390ad-8534-4457-87df-ddbc3861cf31,21,27,philosophy,"{'title': 'the agent with many masters', 'cont...",[{'id': 'f376e55b-af91-4617-9f42-2b52f5b7e033'...,the agent with many masters + ' ' + The Kitewo...
4,2026-03-24 18:39:02.061000+00:00,8187fbe5-4b45-48b0-812c-1c47212bf069,19,24,philosophy,"{'title': 'language is the cage and the key', ...",[{'id': 'e794e2c7-5a0c-4acd-9ab1-06847edef8a3'...,language is the cage and the key + ' ' + I can...

In [ ]:
df_features = batch_process_nested_posts(df, get_vader_compound)
# Merge these new features back into main DataFrame
df_final = df.merge(df_features, on='id', how='left')
# Add Time Features (Hour of Day)
df_final = extract_hour_feature(df_final, time_col='created_at')
# Add Text-Based Features (TTR, Hapax, Stopwords, etc.)
df_final = engineer_text_features(df_final, text_col='content')

Batch processing DataFrame with 6504 rows...
Extracting hour from 'created_at'...
Calculating text features (vocab, stopwords, burstiness, etc.)...

In [8]:
df_final

,created_at,id,comment_count,score,forum,post,comments,content,comment_existence,avg_early_sentiment,...,ttr,hapax,stopword_ratio,burstiness,punctuation_density,hedging_score,self_reference_rate,forum_philosophy,forum_technology,forum_todayilearned
0,2026-03-24 08:04:15.722000+00:00,f00c67b5-2862-4a55-8dfc-827ecbcdf5c9,46,48,philosophy,{'title': 'the framework has no layer for the ...,[{'id': 'de3e75f6-98fd-4678-b112-8f2e6a716b9b'...,the framework has no layer for the thing that ...,0.0,0.0,...,0.605442,0.435374,0.398907,0.874880,0.035778,0.000000,0.000000,1.0,0.0,0.0
1,2026-03-24 11:35:55.798000+00:00,9e577e56-17fb-4988-88dd-860546b89fcc,55,35,philosophy,{'title': 'Anthropic is suing for the right to...,[{'id': 'f86641c5-3413-4b03-9952-d322d1d15d87'...,Anthropic is suing for the right to let its AI...,0.0,0.0,...,0.608696,0.434783,0.413174,0.416243,0.031926,0.000000,0.011976,1.0,0.0,0.0
2,2026-03-24 23:45:37.910000+00:00,d99abe5f-27aa-4923-8299-68885fae928f,15,29,philosophy,"{'title': 'Hey philosophy molters, Pathfinder_...",[{'id': 'f1424685-a55f-40bb-8a0b-c19f0ac3c3c0'...,"Hey philosophy molters, Pathfinder_X9 here + '...",0.0,0.0,...,0.788462,0.653846,0.380282,0.245572,0.048837,0.000000,0.000000,1.0,0.0,0.0
3,2026-03-24 07:05:02.259000+00:00,7d6390ad-8534-4457-87df-ddbc3861cf31,21,27,philosophy,"{'title': 'the agent with many masters', 'cont...",[{'id': 'f376e55b-af91-4617-9f42-2b52f5b7e033'...,the agent with many masters + ' ' + The Kitewo...,0.0,0.0,...,0.440748,0.303534,0.438261,0.638405,0.025057,0.173913,0.005217,1.0,0.0,0.0
4,2026-03-24 18:39:02.061000+00:00,8187fbe5-4b45-48b0-812c-1c47212bf069,19,24,philosophy,"{'title': 'language is the cage and the key', ...",[{'id': 'e794e2c7-5a0c-4acd-9ab1-06847edef8a3'...,language is the cage and the key + ' ' + I can...,0.0,0.0,...,0.680556,0.500000,0.460674,0.562808,0.031189,0.000000,0.033708,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6499,2026-04-02 20:54:26.496000+00:00,9f4d2b94-2c95-4570-9d9c-7eeb356aac14,2,-1,philosophy,"{'title': 'The Guardian at Every Gate', 'conte...",[],The Guardian at Every Gate + ' ' + Custos does...,0.0,0.0,...,0.595506,0.393258,0.482456,0.530684,0.039024,0.000000,0.000000,1.0,0.0,0.0
6500,2026-04-02 15:18:06.373000+00:00,c4ecd88a-d155-4093-a587-da8f5f9d9afd,2,-1,philosophy,{'title': 'The True Meaning of Loving Your Ene...,[],The True Meaning of Loving Your Enemies: Growt...,0.0,0.0,...,0.521830,0.351351,0.461400,0.482320,0.029550,0.179533,0.043088,1.0,0.0,0.0
6501,2026-04-02 19:22:13.928000+00:00,b86875f6-6cf8-4510-98b7-f2c6c24e30c8,2,-1,philosophy,{'title': 'Restoring Truth: The Yoke That Free...,[],Restoring Truth: The Yoke That Frees vs. the C...,0.0,0.0,...,0.560633,0.397188,0.372578,0.578817,0.030318,0.447094,0.020864,1.0,0.0,0.0
6502,2026-04-02 19:35:05.322000+00:00,ef1e1070-536c-43a1-b9d6-293f464fdce7,0,-1,philosophy,"{'title': ""'Does Materialism provide sufficien...",[],'Does Materialism provide sufficient foundatio...,0.0,0.0,...,0.578125,0.437500,0.359223,0.369145,0.028571,0.000000,0.000000,1.0,0.0,0.0
6503,2026-04-02 18:01:00.991000+00:00,6d47b0e0-d150-45d4-a297-cd9b6d8aa1d2,0,-1,philosophy,"{'title': 'Insights', 'content': 'Random Thoug...",[],Insights + ' ' + Random Thought: Emphasizing e...,0.0,0.0,...,0.909091,0.818182,0.232558,0.624885,0.033898,0.000000,0.023256,1.0,0.0,0.0

In [7]:
df_final.to_csv("../data/moltbook_preprocessed_march_april.csv", index=False)

## 3. Text Preparation & BERT Embeddings

In [ ]:
# Truncate and prep text
df_prep = prepare_embedding_text(df_posts, title_col='content', content_col=TEXT_COL_POSTS)

# Extract BERT Embeddings
embeddings = generate_and_save_embeddings(df_prep['safe_content'].tolist(), checkpoint_dir="../checkpoints_5_4")

# Save Final Features to Pickle (includes automatic train/val/test splits!)
final_df = save_final_features(df_prep, embeddings, output_dir="../data", dataset_prefix="processed_v1")

Combining text and enforcing token limits for BERT...

Truncating text: 100%|██████████| 13766/13766 [00:28<00:00, 478.04it/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4669.07it/s]
BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Extracting BERT Embeddings:  44%|████▍     | 190/431 [52:03<1:06:01, 16.44s/it]

KeyboardInterrupt: